export const simulationAgentManifest = Object.freeze({
  "physics.electricity.coulomb-law-3d": Object.freeze({
    adapterVersion: "coulomb-law-3d-adapter.v1",
    actions: ["open", "configure", "readState", "play", "pause", "reset"],
    tools: ["open_science_simulation"],
    video: false,
    exportable: false,
    parameterSchema: {
      type: "object",
      properties: {
        q1: { type: "number", minimum: -10, maximum: 10 },
        q2: { type: "number", minimum: -10, maximum: 10 },
        x1: { type: "number", minimum: -8, maximum: 8 },
        y1: { type: "number", minimum: -5, maximum: 5 },
        z1: { type: "number", minimum: -8, maximum: 8 },
        x2: { type: "number", minimum: -8, maximum: 8 },
        y2: { type: "number", minimum: -5, maximum: 5 },
        z2: { type: "number", minimum: -8, maximum: 8 },
        showField: { type: "boolean" },
        showFlux: { type: "boolean" },
      },
      additionalProperties: false,
    },
    stateSchema: {
      type: "object",
      required: ["running", "q1", "q2", "pos1", "pos2", "k", "showField", "showFlux", "distance", "force"],
      properties: {
        running: { type: "boolean" },
        q1: { type: "number" },
        q2: { type: "number" },
        pos1: { type: "object" },
        pos2: { type: "object" },
        k: { type: "number" },
        showField: { type: "boolean" },
        showFlux: { type: "boolean" },
        distance: { type: "number" },
        force: { type: "object" },
      },
    },
  }),

  "physics.optics.microscope": Object.freeze({
    adapterVersion: "microscope-adapter.v1",
    actions: ["open", "configure", "readState", "reset"],
    tools: ["open_science_simulation"],
    video: false,
    exportable: false,
    parameterSchema: {
      type: "object",
      properties: {
        focus: { type: "number", minimum: 0, maximum: 1 },
        zoom: { type: "number", minimum: 1, maximum: 10 },
        light: { type: "number", minimum: 0.2, maximum: 2 },
      },
      additionalProperties: false,
    },
    stateSchema: {
      type: "object",
      required: ["simulationId", "focus", "zoom", "light"],
      properties: {
        simulationId: { const: "physics.optics.microscope" },
        focus: { type: "number" },
        zoom: { type: "number" },
        light: { type: "number" },
      },
    },
  }),


  "physics.acoustics.doppler": Object.freeze({
    adapterVersion: "doppler-adapter.v1",
    actions: [
      "open",
      "configure",
      "readState",
      "play",
      "pause",
      "reset",
      "record",
      "export",
    ],
    tools: ["run_doppler_experiment", "open_science_simulation"],
    video: true,
    exportable: true,
    parameterSchema: {
      type: "object",
      properties: {
        motion: {
          type: "string",
          enum: ["approaching", "receding", "stationary"],
        },
        emittedFrequencyHz: { type: "number", minimum: 100, maximum: 1000 },
        sourceSpeedMps: { type: "number", minimum: 0, maximum: 150 },
        sourcePositionM: { type: "number", minimum: 0, maximum: 1000 },
        observerPositionM: { type: "number", minimum: 0, maximum: 1000 },
        observerVelocityMps: { type: "number", minimum: -100, maximum: 100 },
      },
      required: ["motion"],
      additionalProperties: false,
    },
    stateSchema: {
      type: "object",
      required: ["simulationId", "status", "observer", "sources"],
      properties: {
        simulationId: { const: "physics.acoustics.doppler" },
        status: { type: "string", enum: ["running", "paused"] },
        observer: { type: "object" },
        sources: { type: "array" },
      },
    },
  }),

  "physics.mechanics.simple-pendulum": Object.freeze({
    adapterVersion: "pendulum-adapter.v1",
    actions: ["open", "configure", "readState", "play", "pause", "reset", "record", "export"],
    tools: ["open_science_simulation"],
    video: true,
    exportable: true,
    parameterSchema: {
      type: "object",
      properties: {
        lengthM: { type: "number", minimum: 0.5, maximum: 3.0 },
        massKg: { type: "number", minimum: 0.1, maximum: 10.0 },
        entryAngle: { type: "number", minimum: -170, maximum: 170 },
        elasticity: { type: "number", minimum: 0.98, maximum: 1.0 },
      },
      additionalProperties: false,
    },
    stateSchema: {
      type: "object",
      required: ["running", "lengthM", "massKg", "entryAngle", "elasticity"],
      properties: {
        running: { type: "boolean" },
        lengthM: { type: "number" },
        massKg: { type: "number" },
        entryAngle: { type: "number" },
        elasticity: { type: "number" },
      },
    },
  }),

  "physics.mechanics.spring-mass": Object.freeze({
    adapterVersion: "spring-mass-adapter.v1",
    actions: ["open", "configure", "readState", "play", "pause", "reset", "record", "export"],
    tools: ["open_science_simulation"],
    video: true,
    exportable: true,
    parameterSchema: {
      type: "object",
      properties: {
        k: { type: "number", minimum: 1, maximum: 100 },
        mass: { type: "number", minimum: 0.1, maximum: 10 },
        displacement: { type: "number", minimum: -5, maximum: 5 },
        velocity: { type: "number", minimum: -10, maximum: 10 },
        damping: { type: "number", minimum: 0, maximum: 2 },
      },
      additionalProperties: false,
    },
    stateSchema: {
      type: "object",
      required: ["running", "k", "mass", "displacement", "velocity", "damping"],
      properties: {
        running: { type: "boolean" },
        k: { type: "number" },
        mass: { type: "number" },
        displacement: { type: "number" },
        velocity: { type: "number" },
        damping: { type: "number" },
      },
    },
  }),

  "physics.mechanics.circular-motion": Object.freeze({
    adapterVersion: "circular-motion-adapter.v1",
    actions: ["open", "configure", "readState", "play", "pause", "reset"],
    tools: ["open_science_simulation"],
    video: false,
    exportable: false,
    parameterSchema: {
      type: "object",
      properties: {
        radius: { type: "number", minimum: 10, maximum: 200 },
        omega0: { type: "number", minimum: -5, maximum: 5 },
        alpha: { type: "number", minimum: -2, maximum: 2 },
        mass: { type: "number", minimum: 0.1, maximum: 10 },
      },
      additionalProperties: false,
    },
    stateSchema: {
      type: "object",
      required: ["running", "radius", "omega0", "alpha", "mass"],
      properties: {
        running: { type: "boolean" },
        radius: { type: "number" },
        omega0: { type: "number" },
        alpha: { type: "number" },
        mass: { type: "number" },
      },
    },
  }),

  "physics.mechanics.projectile": Object.freeze({
    adapterVersion: "projectile-adapter.v1",
    actions: ["open", "configure", "readState", "play", "pause", "reset"],
    tools: ["open_science_simulation"],
    video: false,
    exportable: false,
    parameterSchema: {
      type: "object",
      properties: {
        gravity: { type: "number", minimum: 0, maximum: 25 },
        airResistance: { type: "number", minimum: 0, maximum: 0.2 },
        selectedObject: {
          type: "string",
          enum: ["ball", "car", "plane", "parcel"],
        },
        x: { type: "number", minimum: -500, maximum: 500 },
        y: { type: "number", minimum: 0, maximum: 200 },
        vx: { type: "number", minimum: -50, maximum: 50 },
        vy: { type: "number", minimum: -50, maximum: 50 },
      },
      additionalProperties: false,
    },
    stateSchema: {
      type: "object",
      required: ["running", "gravity", "airResistance", "selectedObject"],
      properties: {
        running: { type: "boolean" },
        gravity: { type: "number" },
        airResistance: { type: "number" },
        selectedObject: { type: "string" },
        objects: { type: "array" },
      },
    },
  }),

  "physics.mechanics.gravity-comparison": Object.freeze({
    adapterVersion: "gravity-comparison-adapter.v1",
    actions: ["open", "configure", "readState", "play", "pause", "reset"],
    tools: ["open_science_simulation"],
    video: true,
    exportable: false,
    parameterSchema: {
      type: "object",
      properties: {
        mode: {
          type: "string",
          enum: ["freeFall", "projectile"],
        },
        freeFallHeight: { type: "number", minimum: 20, maximum: 150 },
        projectileSpeed: { type: "number", minimum: 5, maximum: 100 },
        projectileAngleDeg: { type: "number", minimum: 5, maximum: 85 },
      },
      additionalProperties: false,
    },
    stateSchema: {
      type: "object",
      required: ["running", "mode", "freeFallHeight", "projectileSpeed", "projectileAngleDeg"],
      properties: {
        running: { type: "boolean" },
        mode: { type: "string" },
        freeFallHeight: { type: "number" },
        projectileSpeed: { type: "number" },
        projectileAngleDeg: { type: "number" },
      },
    },
  }),

  "physics.mechanics.seesaw": Object.freeze({
    adapterVersion: "seesaw-adapter.v1",
    actions: ["open", "configure", "readState", "play", "pause", "reset"],
    tools: ["open_science_simulation"],
    video: false,
    exportable: false,
    parameterSchema: {
      type: "object",
      properties: {
        fulcrumHeight: { type: "number", minimum: 0.5, maximum: 4 },
        leftArmLength: { type: "number", minimum: 1, maximum: 5 },
        rightArmLength: { type: "number", minimum: 1, maximum: 5 },
        plankMass: { type: "number", minimum: 5, maximum: 50 },
        damping: { type: "number", minimum: 0, maximum: 1 },
        friction: { type: "number", minimum: 0, maximum: 1 },
      },
      additionalProperties: false,
    },
    stateSchema: {
      type: "object",
      required: [
        "running",
        "fulcrumHeight",
        "leftArmLength",
        "rightArmLength",
        "plankMass",
        "damping",
        "friction",
      ],
      properties: {
        running: { type: "boolean" },
        fulcrumHeight: { type: "number" },
        leftArmLength: { type: "number" },
        rightArmLength: { type: "number" },
        plankMass: { type: "number" },
        damping: { type: "number" },
        friction: { type: "number" },
      },
    },
  }),

  "physics.mechanics.collision": Object.freeze({
    adapterVersion: "collision-adapter.v1",
    actions: ["open", "configure", "readState", "play", "pause", "reset"],
    tools: ["open_science_simulation"],
    video: false,
    exportable: false,
    parameterSchema: {
      type: "object",
      properties: {
        restitution: { type: "number", minimum: 0, maximum: 1 },
        timeScale: { type: "number", minimum: 0, maximum: 5 },
        p1Mass: { type: "number", minimum: 0.1, maximum: 1000 },
        p1Vx: { type: "number", minimum: -100, maximum: 100 },
        p1Vy: { type: "number", minimum: -100, maximum: 100 },
        p2Mass: { type: "number", minimum: 0.1, maximum: 1000 },
        p2Vx: { type: "number", minimum: -100, maximum: 100 },
        p2Vy: { type: "number", minimum: -100, maximum: 100 },
      },
      additionalProperties: false,
    },
    stateSchema: {
      type: "object",
      required: ["running", "restitution", "timeScale", "p1", "p2"],
      properties: {
        running: { type: "boolean" },
        restitution: { type: "number" },
        timeScale: { type: "number" },
        p1: { type: "object" },
        p2: { type: "object" },
      },
    },
  }),

  "physics.mechanics.pulley-system": Object.freeze({
    adapterVersion: "pulley-system-adapter.v1",
    actions: ["open", "configure", "readState", "play", "pause", "reset"],
    tools: ["open_science_simulation"],
    video: false,
    exportable: false,
    parameterSchema: {
      type: "object",
      properties: {
        config: {
          type: "string",
          enum: ["fixed", "movable", "bt_luff", "bt2", "bt_gyn", "bt3"],
        },
        loadMass: { type: "number", minimum: 1, maximum: 500 },
        effortForce: { type: "number", minimum: 0, maximum: 2000 },
        g: { type: "number", minimum: 0, maximum: 20 },
        efficiency: { type: "number", minimum: 0.5, maximum: 1 },
        damping: { type: "number", minimum: 0, maximum: 200 },
        showForces: { type: "boolean" },
      },
      additionalProperties: false,
    },
    stateSchema: {
      type: "object",
      required: ["running", "config", "loadMass", "effortForce", "g", "efficiency", "damping"],
      properties: {
        running: { type: "boolean" },
        config: { type: "string" },
        loadMass: { type: "number" },
        effortForce: { type: "number" },
        g: { type: "number" },
        efficiency: { type: "number" },
        damping: { type: "number" },
        showForces: { type: "boolean" },
      },
    },
  }),

  "physics.mechanics.two-body-gravity": Object.freeze({
    adapterVersion: "two-body-gravity-adapter.v1",
    actions: ["open", "configure", "readState", "play", "pause", "reset"],
    tools: ["open_science_simulation"],
    video: false,
    exportable: false,
    parameterSchema: {
      type: "object",
      properties: {
        m1: { type: "number", minimum: 1, maximum: 2000 },
        v1: { type: "number", minimum: 0, maximum: 100 },
        ang1: { type: "number", minimum: 0, maximum: 360 },
        x1: { type: "number", minimum: -50, maximum: 50 },
        m2: { type: "number", minimum: 0.1, maximum: 2000 },
        v2: { type: "number", minimum: 0, maximum: 100 },
        ang2: { type: "number", minimum: 0, maximum: 360 },
        x2: { type: "number", minimum: -50, maximum: 50 },
        G: { type: "number", minimum: 0.1, maximum: 50 },
        showVectors: { type: "boolean" },
        showTrail: { type: "boolean" },
        showCM: { type: "boolean" },
        followCM: { type: "boolean" },
      },
      additionalProperties: false,
    },
    stateSchema: {
      type: "object",
      required: ["running", "m1", "m2", "G"],
      properties: {
        running: { type: "boolean" },
        m1: { type: "number" },
        m2: { type: "number" },
        G: { type: "number" },
      },
    },
  }),

  "physics.fluid-mechanics.archimedes-principle": Object.freeze({
    adapterVersion: "archimedes-adapter.v1",
    actions: ["open", "configure", "readState", "play", "pause", "reset"],
    tools: ["open_science_simulation"],
    video: false,
    exportable: false,
    parameterSchema: {
      type: "object",
      properties: {
        objDensity: { type: "number", minimum: 50, maximum: 20000 },
        fluidDensity: { type: "number", minimum: 500, maximum: 14000 },
        shape: {
          type: "string",
          enum: ["box", "sphere", "cylinder", "cylinderHorizontal", "pyramid"],
        },
        showForces: { type: "boolean" },
      },
      additionalProperties: false,
    },
    stateSchema: {
      type: "object",
      required: ["running", "objDensity", "fluidDensity", "shape"],
      properties: {
        running: { type: "boolean" },
        objDensity: { type: "number" },
        fluidDensity: { type: "number" },
        shape: { type: "string" },
        showForces: { type: "boolean" },
      },
    },
  }),

  "physics.acoustics.sound-waves": Object.freeze({
    adapterVersion: "sound-waves-adapter.v1",
    actions: ["open", "configure", "readState", "play", "pause", "reset"],
    tools: ["open_science_simulation"],
    video: false,
    exportable: false,
    parameterSchema: {
      type: "object",
      properties: {
        mode: { type: "string", enum: ["generator", "beats", "mic"] },
        freq1: { type: "number", minimum: 100, maximum: 1000 },
        freq2: { type: "number", minimum: 100, maximum: 1000 },
        volume: { type: "number", minimum: 0, maximum: 1 },
        waveType: {
          type: "string",
          enum: ["sine", "square", "sawtooth", "triangle"],
        },
      },
      additionalProperties: false,
    },
    stateSchema: {
      type: "object",
      required: ["running", "mode", "freq1", "freq2", "volume", "waveType"],
      properties: {
        running: { type: "boolean" },
        mode: { type: "string" },
        freq1: { type: "number" },
        freq2: { type: "number" },
        volume: { type: "number" },
        waveType: { type: "string" },
      },
    },
  }),

  "physics.electricity.coulomb-law-2d": Object.freeze({
    adapterVersion: "coulomb-law-2d-adapter.v1",
    actions: ["open", "configure", "readState", "play", "pause", "reset"],
    tools: ["open_science_simulation"],
    video: false,
    exportable: false,
    parameterSchema: {
      type: "object",
      properties: {
        q1: { type: "number", minimum: -10, maximum: 10 },
        q2: { type: "number", minimum: -10, maximum: 10 },
        x1: { type: "number", minimum: -8, maximum: 8 },
        y1: { type: "number", minimum: -5, maximum: 5 },
        x2: { type: "number", minimum: -8, maximum: 8 },
        y2: { type: "number", minimum: -5, maximum: 5 },
        k: { type: "number", minimum: 0.1, maximum: 20 },
      },
      additionalProperties: false,
    },
    stateSchema: {
      type: "object",
      required: ["running", "q1", "q2", "pos1", "pos2", "k"],
      properties: {
        running: { type: "boolean" },
        q1: { type: "number" },
        q2: { type: "number" },
        pos1: { type: "object" },
        pos2: { type: "object" },
        k: { type: "number" },
      },
    },
  }),

  "physics.mechanics.gyroscope": Object.freeze({
    adapterVersion: "gyroscope-adapter.v1",
    actions: ["open", "configure", "readState", "play", "pause", "reset"],
    tools: ["open_science_simulation"],
    video: false,
    exportable: false,
    parameterSchema: {
      type: "object",
      properties: {
        spinSpeed: { type: "number", minimum: 0, maximum: 50 },
        tilt: { type: "number", minimum: 0, maximum: 85 },
        mass: { type: "number", minimum: 0.1, maximum: 5 },
        showVectors: { type: "boolean" },
        showTrail: { type: "boolean" },
      },
      additionalProperties: false,
    },
    stateSchema: {
      type: "object",
      required: [
        "running",
        "spinSpeed",
        "tilt",
        "mass",
        "elapsedSeconds",
        "angularMomentum",
        "torque",
        "precession",
      ],
      properties: {
        running: { type: "boolean" },
        spinSpeed: { type: "number" },
        tilt: { type: "number" },
        mass: { type: "number" },
        elapsedSeconds: { type: "number" },
        angularMomentum: { type: "number" },
        torque: { type: "number" },
        precession: { type: "number" },
        showVectors: { type: "boolean" },
        showTrail: { type: "boolean" },
      },
    },
  }),

  "astronomy.space.solar-system": Object.freeze({
    adapterVersion: "solar-system-adapter.v1",
    actions: ["open", "configure", "readState", "play", "pause", "reset", "record", "export"],
    tools: ["open_science_simulation", "prepare_solar_system_video"],
    video: true,
    exportable: true,
    parameterSchema: {
      type: "object",
      properties: {
        speed: { type: "number", minimum: 0, maximum: 30 },
        scaleMode: {
          type: "string",
          enum: ["educational", "semiRealistic", "realistic"],
        },
        focusTarget: {
          type: "string",
          enum: ["system", "sun", "mercury", "venus", "earth", "moon", "mars", "jupiter", "saturn", "uranus", "neptune"],
        },
        showTrails: { type: "boolean" },
        showOrbits: { type: "boolean" },
        showAxis: { type: "boolean" },
        showStars: { type: "boolean" },
        showLabels: { type: "boolean" },
      },
      additionalProperties: false,
    },
    stateSchema: {
      type: "object",
      required: ["running", "speed", "scaleMode", "focusTarget", "isTouring"],
      properties: {
        running: { type: "boolean" },
        speed: { type: "number" },
        scaleMode: { type: "string" },
        focusTarget: { type: "string" },
        showTrails: { type: "boolean" },
        showOrbits: { type: "boolean" },
        showAxis: { type: "boolean" },
        showStars: { type: "boolean" },
        showLabels: { type: "boolean" },
        isTouring: { type: "boolean" },
        video: { type: "object" },
      },
    },
  }),

  "physics.waves.multi-source-interference": Object.freeze({
    adapterVersion: "multi-source-interference-adapter.v1",
    actions: ["open", "configure", "readState", "play", "pause", "reset", "record", "export"],
    tools: ["open_science_simulation"],
    video: true,
    exportable: true,
    parameterSchema: {
      type: "object",
      properties: {
        renderMode: { type: "string", enum: ["pattern", "water"] },
        waveSpeed: { type: "number", minimum: 10, maximum: 30 },
        damping: { type: "number", minimum: 0, maximum: 0.1 },
        preset: { type: "string", enum: ["deep-cinema", "aurora", "violet-neon", "solar-gold", "moon-pool"] },
        causticStyle: { type: "string", enum: ["silk", "ribbons", "prism", "glow", "off"] },
        bloom: { type: "number", minimum: 0.2, maximum: 3 },
        depth: { type: "number", minimum: 0.2, maximum: 2.4 },
        contrast: { type: "number", minimum: 0.5, maximum: 2.6 },
        caustics: { type: "number", minimum: 0, maximum: 1.1 },
        colorShift: { type: "number", minimum: 0, maximum: 1 },
        orbGlow: { type: "number", minimum: 0.1, maximum: 3 },
        highlightSoftness: { type: "number", minimum: 0, maximum: 1 },
        surfaceDetail: { type: "number", minimum: 0, maximum: 1.4 },
        lightAngle: { type: "number", minimum: -1, maximum: 1 },
        backgroundGlow: { type: "number", minimum: 0, maximum: 1.4 },
        durationSeconds: { type: "number", minimum: 5, maximum: 600 },
        fps: { type: "number", minimum: 30, maximum: 60 },
      },
      additionalProperties: false,
    },
    stateSchema: {
      type: "object",
      required: ["simulationId", "running", "renderMode", "medium", "sources", "waterStyle", "video"],
      properties: {
        simulationId: { const: "physics.waves.multi-source-interference" },
        running: { type: "boolean" },
        elapsedSeconds: { type: "number" },
        renderMode: { type: "string" },
        medium: { type: "object" },
        sources: { type: "array" },
        waterStyle: { type: "object" },
        video: { type: "object" },
      },
    },
  }),

  "astronomy.space.earth-orbit-lab": Object.freeze({
    adapterVersion: "earth-orbit-lab-adapter.v1",
    actions: ["open", "configure", "readState", "play", "pause", "reset"],
    tools: ["open_science_simulation"],
    video: false,
    exportable: false,
    parameterSchema: {
      type: "object",
      properties: {
        simMode: { type: "string", enum: ["educational", "semi", "realistic"] },
        timeScale: { type: "number", minimum: 1, maximum: 500000 },
        showTrails: { type: "boolean" },
        showVectors: { type: "boolean" },
        showLOS: { type: "boolean" },
        showOrbits: { type: "boolean" },
        showOnlyVisible: { type: "boolean" },
        showMoon: { type: "boolean" },
        showLagrangePoints: { type: "boolean" },
        showLabels: { type: "boolean" },
        telescopeLat: { type: "number", minimum: -90, maximum: 90 },
        telescopeLon: { type: "number", minimum: -180, maximum: 180 },
      },
      additionalProperties: false,
    },
    stateSchema: {
      type: "object",
      required: ["running", "simMode", "timeScale"],
      properties: {
        running: { type: "boolean" },
        simMode: { type: "string" },
        timeScale: { type: "number" },
        showTrails: { type: "boolean" },
        showVectors: { type: "boolean" },
        showLOS: { type: "boolean" },
        showOrbits: { type: "boolean" },
        showOnlyVisible: { type: "boolean" },
        showMoon: { type: "boolean" },
        showLagrangePoints: { type: "boolean" },
        showLabels: { type: "boolean" },
        telescopeLat: { type: "number" },
        telescopeLon: { type: "number" },
      },
    },
  }),
});

export function getSimulationAgentManifestEntry(id) {
  return simulationAgentManifest[id] || null;
}
