export const IMAGE_MOTION_FORMATS = {
  shorts: {
    label: "YouTube Shorts 9:16",
    shortLabel: "9:16",
    width: 1080,
    height: 1920,
    aspect: 9 / 16,
    recorderMode: "shorts",
  },
  landscape: {
    label: "Landscape 16:9",
    shortLabel: "16:9",
    width: 1920,
    height: 1080,
    aspect: 16 / 9,
    recorderMode: "landscape",
  },
  square: {
    label: "Square 1:1",
    shortLabel: "1:1",
    width: 1080,
    height: 1080,
    aspect: 1,
    recorderMode: "square",
  },
};

export const SCENE_MODES = {
  flat: {
    label: "Flat",
    depth: 0.15,
    description: "A clean framed image with subtle atmosphere.",
  },
  depthParallax: {
    label: "Depth Parallax",
    depth: 0.75,
    description: "Layered image, particles, and camera motion for depth.",
  },
  spaceFlythrough: {
    label: "Space Flythrough",
    depth: 1.15,
    description: "Forward movement through dust, stars, and scene layers.",
  },
  objectDrift: {
    label: "Object Drift",
    depth: 0.9,
    description: "Foreground object becomes the visual focus.",
  },
  ringFlight: {
    label: "Ring Flight",
    depth: 1.25,
    description: "Fast ring debris and lateral parallax for Saturn scenes.",
  },
  deepSpace: {
    label: "Deep Space",
    depth: 1,
    description: "Slow documentary motion with dense star atmosphere.",
  },
};

export const CAMERA_MOTION_PRESETS = {
  slowCosmicPush: {
    label: "Slow Cosmic Push",
    camera: "dollyIn",
    zStart: 8.2,
    zEnd: 5.9,
    xDrift: 0.22,
    yDrift: -0.12,
    roll: 0.018,
  },
  orbitReveal: {
    label: "Orbit Reveal",
    camera: "orbitDrift",
    zStart: 7.4,
    zEnd: 6.3,
    xDrift: 0.58,
    yDrift: 0.22,
    roll: 0.035,
  },
  flyThroughRings: {
    label: "Fly Through Rings",
    camera: "flyThrough",
    zStart: 9.2,
    zEnd: 4.9,
    xDrift: -0.72,
    yDrift: 0.18,
    roll: 0.055,
  },
  deepSpaceDrift: {
    label: "Deep Space Drift",
    camera: "truckLeft",
    zStart: 7.8,
    zEnd: 6.8,
    xDrift: -0.55,
    yDrift: 0.2,
    roll: 0.012,
  },
  documentaryPush: {
    label: "Documentary Push",
    camera: "slowPush",
    zStart: 7.5,
    zEnd: 6.15,
    xDrift: 0.05,
    yDrift: -0.08,
    roll: 0,
  },
  epicReveal: {
    label: "Epic Reveal",
    camera: "tilt",
    zStart: 8.6,
    zEnd: 5.85,
    xDrift: 0.16,
    yDrift: 0.48,
    roll: -0.026,
  },
  planetFlyby: {
    label: "Planet Flyby",
    camera: "truckRight",
    zStart: 7.9,
    zEnd: 6.05,
    xDrift: 0.86,
    yDrift: -0.18,
    roll: -0.034,
  },
  randomMicroMotion: {
    label: "Random Micro Motion",
    camera: "micro",
    zStart: 7.4,
    zEnd: 6.8,
    xDrift: 0.2,
    yDrift: 0.18,
    roll: 0.02,
  },
};

export const PARTICLE_PRESETS = {
  stars: {
    label: "Stars",
    count: 320,
    speed: 0.22,
    opacity: 0.72,
    size: 0.026,
    randomness: 0.78,
    depth: 1.05,
    colorA: "#dbeafe",
    colorB: "#67e8f9",
  },
  dust: {
    label: "Cosmic Dust",
    count: 240,
    speed: 0.16,
    opacity: 0.42,
    size: 0.044,
    randomness: 0.9,
    depth: 0.78,
    colorA: "#fef3c7",
    colorB: "#a78bfa",
  },
  ice: {
    label: "Ice Crystals",
    count: 210,
    speed: 0.28,
    opacity: 0.58,
    size: 0.036,
    randomness: 0.66,
    depth: 0.95,
    colorA: "#e0f2fe",
    colorB: "#22d3ee",
  },
  ringDebris: {
    label: "Ring Debris",
    count: 440,
    speed: 0.38,
    opacity: 0.66,
    size: 0.032,
    randomness: 0.52,
    depth: 1.25,
    colorA: "#f8fafc",
    colorB: "#38bdf8",
  },
  smallRocks: {
    label: "Small Rocks",
    count: 130,
    speed: 0.18,
    opacity: 0.52,
    size: 0.062,
    randomness: 0.72,
    depth: 0.88,
    colorA: "#d6d3d1",
    colorB: "#94a3b8",
  },
};

export const LIGHT_PRESETS = {
  cinematicGlow: {
    label: "Cinematic Glow",
    glow: 0.86,
    rays: 0.45,
    vignette: 0.62,
    lens: 0.45,
    color: "#67e8f9",
  },
  lensSweep: {
    label: "Lens Sweep",
    glow: 0.7,
    rays: 0.78,
    vignette: 0.54,
    lens: 0.78,
    color: "#f472b6",
  },
  solarBloom: {
    label: "Solar Bloom",
    glow: 1,
    rays: 0.64,
    vignette: 0.58,
    lens: 0.58,
    color: "#fde68a",
  },
  deepVignette: {
    label: "Deep Vignette",
    glow: 0.42,
    rays: 0.18,
    vignette: 0.86,
    lens: 0.24,
    color: "#a78bfa",
  },
  none: {
    label: "Clean",
    glow: 0.18,
    rays: 0,
    vignette: 0.35,
    lens: 0,
    color: "#ffffff",
  },
};

export const OBJECT_MOTION_PRESETS = {
  float: {
    label: "Float",
    orbitRadius: 0.08,
    xTravel: 0,
    yTravel: 0.34,
    zTravel: 0,
    rotation: 0.18,
    scalePulse: 0.04,
  },
  rotate: {
    label: "Rotate",
    orbitRadius: 0.02,
    xTravel: 0,
    yTravel: 0,
    zTravel: 0,
    rotation: 1.45,
    scalePulse: 0.02,
  },
  moveLeft: {
    label: "Move Left",
    orbitRadius: 0,
    xTravel: -2.4,
    yTravel: 0.16,
    zTravel: 0,
    rotation: 0.08,
    scalePulse: 0.02,
  },
  moveRight: {
    label: "Move Right",
    orbitRadius: 0,
    xTravel: 2.4,
    yTravel: -0.1,
    zTravel: 0,
    rotation: -0.08,
    scalePulse: 0.02,
  },
  approachCamera: {
    label: "Approach Camera",
    orbitRadius: 0.04,
    xTravel: 0.28,
    yTravel: 0.18,
    zTravel: 1.2,
    rotation: 0.12,
    scalePulse: 0.22,
  },
  moveAway: {
    label: "Move Away",
    orbitRadius: 0.04,
    xTravel: -0.2,
    yTravel: -0.1,
    zTravel: -1.1,
    rotation: -0.1,
    scalePulse: -0.16,
  },
  circularDrift: {
    label: "Circular Drift",
    orbitRadius: 0.64,
    xTravel: 0,
    yTravel: 0,
    zTravel: 0.15,
    rotation: 0.34,
    scalePulse: 0.05,
  },
  orbit: {
    label: "Orbit",
    orbitRadius: 1.08,
    xTravel: 0,
    yTravel: 0,
    zTravel: 0.35,
    rotation: 0.52,
    scalePulse: 0.06,
  },
  spaceshipFlyForward: {
    label: "Spaceship Fly Forward",
    orbitRadius: 0.05,
    xTravel: 2.8,
    yTravel: 0.4,
    zTravel: 1.45,
    rotation: -0.2,
    scalePulse: 0.32,
  },
  randomDrift: {
    label: "Random Drift",
    orbitRadius: 0.42,
    xTravel: 0.72,
    yTravel: 0.52,
    zTravel: 0.22,
    rotation: 0.62,
    scalePulse: 0.08,
  },
};

export const OBJECT_TYPE_PRESETS = {
  custom: {
    label: "Custom uploaded object",
    objectMotion: "float",
    scale: 0.82,
  },
  spaceship: {
    label: "Spaceship",
    objectMotion: "spaceshipFlyForward",
    scale: 0.92,
  },
  astronaut: {
    label: "Astronaut",
    objectMotion: "float",
    scale: 0.74,
  },
  satellite: {
    label: "Satellite",
    objectMotion: "orbit",
    scale: 0.68,
  },
  planet: {
    label: "Planet",
    objectMotion: "approachCamera",
    scale: 1.15,
  },
  moon: {
    label: "Moon",
    objectMotion: "circularDrift",
    scale: 0.92,
  },
  football: {
    label: "Football",
    objectMotion: "randomDrift",
    scale: 0.55,
  },
};

export const TARGET_DURATION_OPTIONS = [15, 30, 45, 60, 90, 120];

export const DEFAULT_SCENE_SETTINGS = {
  sceneMode: "depthParallax",
  cameraMotion: "slowCosmicPush",
  particlePreset: "ringDebris",
  lightPreset: "cinematicGlow",
  objectMotion: "float",
};

export const FUTURE_AI_SCENE_HOOKS = {
  depthMapGenerator: "planned",
  objectSegmentation: "planned",
  layerSeparation: "planned",
  aiCameraMotion: "planned",
  aiSceneGeneration: "planned",
};
